# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0377b329ec0971fa03da42109494a302ed2a5b1eea0fe32c4cae23021ba9627999b26bb58ce02ce689a5c34d098cc48f4b56be8d2e55f23da98ebd855010b73

test:
  secret_key_base: 968f65b4ae085a4b0a55ff5b1740622c727445f1f3c57b642d6cdc88b65ff5a1e9cf980d430b2d1c664e2aeb501d153c4100f7553c606f41a1e758b4ff45b2e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
